version: '2'
services:
  dev:
    build: .
    # ports:
    #   - "5000:5000" # ports not needed for dev
    volumes:
      - ./.:/usr/src/fantasy-nodejs-client
    working_dir: /usr/src/fantasy-nodejs-client
    entrypoint:
      - ./docker-entrypoint.sh